### ISSUE TITLE
Bolt Protocol Specification Update

### ISSUE THREAD

**Issue by martin-neotech** [aphorisme/raio-rs#1]
https://github.com/neo4j-drivers/neo4j-drivers.github.io

https://7687.org/

Cheers, Martin

**Comment by aphorisme** [comment]
Thank you very much! This is nice to have and I somehow waited for an official source. This even have become more relevant, since I might use `raio-rs` heavily next year, so plans are to update and refactor it until end of this year.

**Comment by aphorisme** [comment]
The PackStream part has become its own package: https://github.com/aphorisme/packs-rs

This keeps the bolt protocol itself open which will the very near future of this package.

**Comment by aphorisme** [comment]
Done with v0.2.0
