### ISSUE TITLE
How to return query result as response in an Actix endpoint?

### ISSUE THREAD

**Issue by telmotrooper** [aphorisme/raio-rs#3]
This is probably a noob question and maybe not directly related to `raio`, but I'm trying to use the library together with `actix_web` and I'm having some issues. I'm using `raio = "0.2.0"`, `actix-rt = "1.1.1"` and `actix-web = "3.3.2"`.

I've successfully connected to my Neo4j instance, but I just can't find a way to return the data queried from Neo4j in my endpoint.

This is what it looks like right now:
```
use actix_web::{client::Client, web::Json};
use actix_web::{error, get, post, HttpResponse, Responder, Result, HttpRequest};

use raio::client::ClientConfig;
use raio::client::auth::Basic;
use raio::client::error::ClientError;
use raio::messaging::query::Query;

#[get("/neo4j-test")]
pub async fn neo4j_test() -> impl Responder {
    let auth = Basic::new("neo4j", "telmo");
    let client = raio::client::Client::create(
        "localhost:7687",
        auth,
        ClientConfig::default("raio-rs-test", "0.2.0")
    );

    let mut query = Query::new("MATCH (n) RETURN n;");

    let result = client.query(&query).await.expect("Error while querying.");

    let first = result.records().first().expect("Expected at least one result.");

    HttpResponse::Ok().body(first)
}
```
And the error I get is:
```
error[E0277]: the trait bound `actix_web::dev::Body: From<&RecordResult>` is not satisfied
```

As of now I'd be happy if I could return the results straight into the response body just to try it out. I've tried using `first.data` as well and a few ways to convert the output to string, but I couldn't get to work.

Can you help me out? I appreciate it.

**Comment by telmotrooper** [comment]
If I try `HttpResponse::Ok().json(first)` I get `the trait 'Serialize' is not implemented for 'RecordResult'`.

**Comment by aphorisme** [comment]
Hello telmotrooper,

this has been a while, hopefully the answer is still of use: The signature of actix-web's `HttpResponse::Ok().body` is (see here: https://docs.rs/actix-web/3.3.2/actix_web/dev/struct.HttpResponseBuilder.html#method.body)

```rust
pub fn body<B>(&mut self, body: B) -> Response<Body> where
    B: Into<Body>, 
```

which means that `&RecordResult`, returned by raio's `result.records().first()` has to be turned into a `Body`, which is not implemented, neither in actix-web nor in raio. The solution here is to use the functions of `RecordResult`, (see https://docs.rs/raio/0.2.0/raio/client/record_result/struct.RecordResult.html) to inspect the result and built a `HttpResponse` from ground-up, depending on what you want to return.
